apiVersion: v1
kind: Pod
metadata: 
  name: primeiro-pod
  labels:
    app: primeiro-pod
spec:
  containers:
    - name: ngix-container
      image: nginx:latest
      ports:
        - containerPort: 80