apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: pod-1-statefulset
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-app
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts: 
            - mountPath: /volume-pod
              name: volume-pod
      volumes:
        - name: volume-pod
          persistentVolumeClaim:
            claimName: volume-pvc
  selector:
    matchLabels:
      app: nginx-app
  serviceName: svc-nginx-app