apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pod-1-deployment
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-app
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-containe
          image: nginx:stabl
          volumeMounts: 
            - mountPath: /home
              name: volume-pod
      volumes:
        - name: volume-pod
          hostPath:
            path: /C/volume-pods
  selector:
    matchLabels:
      app: nginx-app