apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:
  template:
    metadata:
      labels:
       app: aplicacao-pod
    spec:
      containers:
        - name: container-aplicacao-loja
          image: aluracliregistryls.azurecr.io/loja/app:v1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name : aluracliregistryls.secret
  selector:
    matchLabels:
      app: aplicacao-pod
