apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: pod-1-replicaset
spec:
  template:
    metadata:
      name: nginx-app
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-containe
          image: nginx:latest
  replicas: 6
  selector:
    matchLabels:
      app: nginx-app